### PR TITLE
Derive PartialEq for InfoResponse

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Derive PartialEq for InfoResponse

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code

### CODE REVIEW

**Review by thibault-martinez — APPROVED** [review]
Out of curiosity, why ?

**Review by pvdrz — APPROVED** [review]

**Comment by Thoralf-M** [comment]
> Out of curiosity, why ?

I wanted to store the `ProtocolResponse` inside of iota.rs so we don't have to request it from the node again every time we need it next to some other data like if local pow should be used or not and that's stored inside of a struct with PartialEq, but I just noticed that we don't need it there
But could still be useful for something else in the future I think

**Review by samuel-rufi — APPROVED** [review]

**Comment by thibault-martinez** [comment]
> > Out of curiosity, why ?
> 
> I wanted to store the `ProtocolResponse` inside of iota.rs so we don't have to request it from the node again every time we need it next to some other data like if local pow should be used or not and that's stored inside of a struct with PartialEq, but I just noticed that we don't need it there But could still be useful for something else in the future I think

What if since you stored the info, it changed ?

**Comment by Thoralf-M** [comment]
> > > Out of curiosity, why ?
> > 
> > 
> > I wanted to store the `ProtocolResponse` inside of iota.rs so we don't have to request it from the node again every time we need it next to some other data like if local pow should be used or not and that's stored inside of a struct with PartialEq, but I just noticed that we don't need it there But could still be useful for something else in the future I think
> 
> What if since you stored the info, it changed ?

You mean in the future if it would get updated via a milestone?
The stored state also gets updated (every 60 seconds by default)

**Pull request merged**
