### PR TITLE
Re-run build script if git commit changes

### PR DESCRIPTION
**Pull request by jeandudey**
# Description of change

Tell cargo to re run the build script if the current commit changes.

## Links to any relevant issues

fixes issue #184 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

- `cargo run -- -v` and check the version, should be equal to the one in `git rev-parse HEAD`.
- `echo "some changes" >> file.txt` and `git add file.txt && git commit -m "test"`
- `cargo run -- -v` and check that the commit shown in the version is updated.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes
- [x] I have updated the CHANGELOG.md, if my changes are significant enough

### CODE REVIEW

**Comment by thibault-martinez** [comment]
Hi @jeandudey, thanks for the PR.
To be honest I am a bit confused, not by your PR but by #184 itself. I seem to not have this problem at all and the 3 steps you listed are working just fine without your changes. Am I missing something ?

**Comment by jeandudey** [comment]
>To be honest I am a bit confused, not by your PR but by #184 itself. I seem to not have this problem at all and the 3 steps you listed are working just fine without your changes. Am I missing something ?

If a new commit is made that doesn't touch a file from `bee-node` or other files that might trigger a rebuild from cargo the commit wont get updated in the `bee` binary.

For example:

<details>
<summary>Problem happening</summary>

```
Welcome to fish, the friendly interactive shell
jeandudey@jean ~/D/i/bee> cargo run -- -v
    Blocking waiting for file lock on package cache
   Compiling bee-node v0.1.2 (/home/jeandudey/Dev/iotaledger/bee/bee-node)
    Finished dev [unoptimized + debuginfo] target(s) in 2m 53s
     Running `target/debug/bee -v`
thread 'main' panicked at 'Failed to create the node config builder: Reading the specified config file failed: No such file or directory (os error 2).', bee-node/src/main.rs:50:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fish: “cargo run -- -v” terminated by signal SIGABRT (Abort)
jeandudey@jean ~/D/i/bee> cp bee-node/config.example.toml config.toml
jeandudey@jean ~/D/i/bee> cargo run -- -v
    Finished dev [unoptimized + debuginfo] target(s) in 0.24s
     Running `target/debug/bee -v`

██████╗ ███████╗███████╗
██╔══██╗██╔════╝██╔════╝
██████╦╝█████╗  █████╗
██╔══██╗██╔══╝  ██╔══╝
██████╦╝███████╗███████╗
╚═════╝ ╚══════╝╚══════╝
     0.1.2-037f46c      

jeandudey@jean ~/D/i/bee> git rev-parse HEAD
037f46c43d579b66badc200ff7e0c6b0fc5c8a51
jeandudey@jean ~/D/i/bee> echo "some changes" >> file.txt
jeandudey@jean ~/D/i/bee> git add file.txt
jeandudey@jean ~/D/i/bee> git commit -s -m "some changes"
[2021_05_23-git-ref 46f56151] some changes
 1 file changed, 1 insertion(+)
 create mode 100644 file.txt
jeandudey@jean ~/D/i/bee> cargo run -- -v
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `target/debug/bee -v`

██████╗ ███████╗███████╗
██╔══██╗██╔════╝██╔════╝
██████╦╝█████╗  █████╗
██╔══██╗██╔══╝  ██╔══╝
██████╦╝███████╗███████╗
╚═════╝ ╚══════╝╚══════╝
     0.1.2-037f46c      

jeandudey@jean ~/D/i/bee> git rev-parse HEAD
46f56151df32b39ea4173a8b34c93c11c69a3977
jeandudey@jean ~/D/i/bee> 
```

</details>

At the last `cargo run -- -v` shows a difference with `git rev-parse HEAD`

With this PR:

<details>
<summary>Commit is updated</summary>

```
jeandudey@jean ~/D/i/bee> cargo run -- -v
   Compiling bee-node v0.1.2 (/home/jeandudey/Dev/iotaledger/bee/bee-node)
    Finished dev [unoptimized + debuginfo] target(s) in 2m 48s
     Running `target/debug/bee -v`

██████╗ ███████╗███████╗
██╔══██╗██╔════╝██╔════╝
██████╦╝█████╗  █████╗
██╔══██╗██╔══╝  ██╔══╝
██████╦╝███████╗███████╗
╚═════╝ ╚══════╝╚══════╝
     0.1.2-d6cbb6a      

jeandudey@jean ~/D/i/bee> git rev-parse HEAD
d6cbb6a19b3d9f7293cdc15705a95c2ea30316fe
jeandudey@jean ~/D/i/bee> echo "some changes" >> file.txt
jeandudey@jean ~/D/i/bee> git add file.txt
jeandudey@jean ~/D/i/bee> git commit -s -m "some changes"
[2021_06_23-git-ref c50411c3] some changes
 1 file changed, 1 insertion(+)
 create mode 100644 file.txt
jeandudey@jean ~/D/i/bee> cargo run -- -v
   Compiling bee-node v0.1.2 (/home/jeandudey/Dev/iotaledger/bee/bee-node)
    Finished dev [unoptimized + debuginfo] target(s) in 2m 48s
     Running `target/debug/bee -v`

██████╗ ███████╗███████╗
██╔══██╗██╔════╝██╔════╝
██████╦╝█████╗  █████╗
██╔══██╗██╔══╝  ██╔══╝
██████╦╝███████╗███████╗
╚═════╝ ╚══════╝╚══════╝
     0.1.2-c50411c      

jeandudey@jean ~/D/i/bee> git rev-parse HEAD
c50411c34eb6d639302561ba506c04dd53e42ac3
jeandudey@jean ~/D/i/bee> 
```

</details>

Now `cargo run -- -v` and `git rev-parse HEAD` match.

**Comment by thibault-martinez** [comment]
I see, thanks for clearing that out! I was running the node from the node crate so it was always rebuilding :)

**Comment by thibault-martinez** [comment]
Two questions to be sure I understand:

1. From the doc I read

> The rerun-if-changed instruction tells Cargo to re-run the build script if the file at the given path has changed. Currently, Cargo only uses the filesystem last-modified "mtime" timestamp to determine if the file has changed. It compares against an internal cached timestamp of when the build script last ran.

But the last modified timestamp of HEAD doesn't change when you commit something, only when you change branch.

Doesn't change
```bash
thibault@mbp ~/i/bee (chrysalis-pt-2)> ls -la ./.git/HEAD
-rw-r--r--  1 thibault  staff  31 Jun 24 12:16 ./.git/HEAD
thibault@mbp ~/i/bee (chrysalis-pt-2)> echo "some changes" >> file.txt
thibault@mbp ~/i/bee (chrysalis-pt-2)> git add file.txt && git commit -m "test"
[chrysalis-pt-2 9a204e83] test
 1 file changed, 1 insertion(+)
thibault@mbp ~/i/bee (chrysalis-pt-2)> ls -la ./.git/HEAD
-rw-r--r--  1 thibault  staff  31 Jun 24 12:16 ./.git/HEAD
thibault@mbp ~/i/bee (chrysalis-pt-2)> date
Thu Jun 24 12:52:43 CEST 2021
```

Change
```bash
thibault@mbp ~/i/bee (chrysalis-pt-2)> ls -la ./.git/HEAD
-rw-r--r--  1 thibault  staff  31 Jun 24 12:16 ./.git/HEAD
thibault@mbp ~/i/bee (chrysalis-pt-2)> date
Thu Jun 24 12:52:43 CEST 2021
thibault@mbp ~/i/bee (chrysalis-pt-2)> git checkout -b test
Switched to a new branch 'test'
thibault@mbp ~/i/bee (test)> ls -la .git/HEAD
-rw-r--r--  1 thibault  staff  21 Jun 24 12:54 .git/HEAD
thibault@mbp ~/i/bee (test)> date
Thu Jun 24 12:55:57 CEST 2021
```

2.  I have no `.git/heads/` on my system

With the combination of these 2, I am not sure how this is supposed to work.

**Comment by jeandudey** [comment]
>But the last modified timestamp of HEAD doesn't change when you commit something, only when you change branch.

`.git/refs/heads/` contains a file with the current branch name, which contains it's current commit, if the file changes the commit changes. Also there's the case that you move to a different branch and no code changes (but the latest commit does), this is detected with `.git/HEAD`, which as you mentioned changes with the branch.

This also handles the case where you checkout to a commit `git checkout 07b9d816f3c60614f60560cb181c4b5dd753cb54` for example, in this case, `.git/HEAD` will change to contain that commit and no `.git/refs/heads` file will exist for that commit unless you create a branch for it.

>I have no .git/heads/ on my system

Sorry, fixed a typo on https://github.com/iotaledger/bee/pull/644/commits/caab218e427576d34da5116c850f218a0e0d3be8 . If the changes seems fine I can squash right away.

**Comment by thibault-martinez** [comment]
Alright yeah seems to work now, thanks!
No need to squash on your side, we always squash directly from the PR :)
Good first PR!

**Review by thibault-martinez — APPROVED** [review]

**Comment by thibault-martinez** [comment]
@jeandudey Do you want to replicate the same on the `coordicide` branch ? Code is very similar but with some more error handling.

**Comment by jeandudey** [comment]
>@jeandudey Do you want to replicate the same on the coordicide branch ? Code is very similar but with some more error handling.

On the way to do so :-D

**Pull request merged**
