### PR TITLE
Feature gate `axum` in `bee-api-types`

### PR DESCRIPTION
**Pull request by cycraig**
# Description of change

Adds a default `"axum"` feature to `bee-api-types`. This makes the `axum` dependency optional, which is only for the `axum::response::IntoResponse` trait required by `bee-rest-api`.

This is to prevent automatically pulling in `axum` and its dependencies unnecessarily in downstream crates, which is preventing the compilation of `iota.rs`/`iota-client` for the `wasm32-unknown-unknown` target.

- The feature name `"axum"` is arbitrary, could also be `"into-response"` for instance, but it is very much linked to the `axum`-specific trait.
- The imports and trait implementation code could be placed in a submodule to make the feature-gating clearer, and use a macro to simplify repetition, but I kept the changes minimal.

## Type of change

This is only technically a breaking change due to the feature-gate.

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

`bee-api-types` compiles fine with different feature combinations:
- `cargo check`
- `cargo check --no-default-features`
- `cargo check --no-default-features --features "peer"`
- `cargo check --no-default-features --features "axum"`

Only two other crates (in `bee`) depend on `bee-api-types` directly:
- `bee-rest-api` requires the `"axum"` feature now, so it still compiles fine with no further changes.
- `bee-plugin-dashboard` compiles fine with no changes.

Also confirmed locally that `iota.rs` compiles to `wasm32-unknown-unknown` with this change (with only the `message-interface` feature enabled though).

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes
- [x] I have updated the CHANGELOG.md, if my changes are significant enough

### CODE REVIEW

**Comment by thibault-martinez** [comment]
Hi @cycraig, thanks for the PR!

> * The imports and trait implementation code could be placed in a submodule to make the feature-gating clearer, and use a macro to simplify repetition, but I kept the changes minimal.

I think I would actually prefer that, do you think you could do it?
I am happy doing it if you don't have the time right now.

**Comment by cycraig** [comment]
Thanks for the quick response!

> I think I would actually prefer that, do you think you could do it?

Done, let me know what you think.

**Review by thibault-martinez — APPROVED** [review]

**Review by samuel-rufi — APPROVED** [review]
Great work!

**Comment by thibault-martinez** [comment]
Thanks!

**Pull request merged**
