### PR TITLE
Re-run build script if git commit changes (coordicide)

### PR DESCRIPTION
**Pull request by jeandudey**
# Description of change

Same fix as #644 but for coordicide branch.

## Links to any relevant issues

fixes issue #184 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

No way to test (yet), but does the same as #644 .

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes
- [x] I have updated the CHANGELOG.md, if my changes are significant enough

### CODE REVIEW

**Comment by jeandudey** [comment]
Test failed seems unrelated

**Comment by thibault-martinez** [comment]
Yeah that's weird, tests are passing on the last commit, we'll have a look.

**Comment by thibault-martinez** [comment]
Hi @jeandudey, tests have been fixed, can you rebase please ?

**Comment by jeandudey** [comment]
Done✅

**Review by thibault-martinez — APPROVED** [review]

**Comment by thibault-martinez** [comment]
Thanks :)

**Pull request merged**
